### ISSUE TITLE
Writing concise CSS

### ISSUE THREAD

**Issue by jim-rosales** [dnesbitt2/Colmar_Academy#4]
When writing CSS if you ever find yourself writing the same styles in multiple places it is best to combine them so making changes down the road is easier. 

For example here both your `h1` and `h2` have the same color and font-weight so instead of declaring these styles separately you could have done the following:

```CSS
h1, h2 {
  color: #2B1C00;
  font-weight: 700;
}

h1 {
  font-size: 2.15rem;
}


h2 {
  font-size: 1.9rem;
}
```

https://github.com/dnesbitt2/Colmar_Academy/blob/fae56d10844d4b09f32863278aef0120b90b936c/resources/css/style.css#L22-L32
